apiVersion: v1
kind: Namespace
metadata:
  name: cluster-nfs
  labels:
    name: cluster-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backing
  namespace: cluster-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: iscsi-local
  volumeName: asustor-iscsi-cluster-nfs
