apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-codetalk
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  instances: 3
  priorityClassName: portfolio-critical
  inheritedMetadata:
    labels:
      portfolio: "true"
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    tolerations:
      - key: nfs
        value: broken
        effect: NoSchedule
  probes:
    liveness:
      isolationCheck:
        enabled: true
        connectionTimeout: 5000
        requestTimeout: 5000
  bootstrap:
    initdb:
      database: codetalk
      owner: codetalk_user
      secret:
        name: cnpg-codetalk-app
  storage:
    size: 5Gi
    storageClass: synology-iscsi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      memory: 512Mi
  monitoring:
    enablePodMonitor: true
  backup:
    volumeSnapshot:
      className: synology-snapshotclass
