apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-synology
  namespace: monitoring
  labels:
    app: gotify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 1Gi
