apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: intervalai-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
  - host: intervalai-k8s.el-jefe.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: intervalai-client
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: intervalai-server
            port:
              number: 8080
