apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: ARGOCD_ADMIN_USERNAME
    secretKey: username
  - remoteRef:
      key: ARGOCD_ADMIN_PASSWORD
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: argocd-credentials

