apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: BACKBLAZE_ACCESS_KEY_ID
    secretKey: accessKeyID
  - remoteRef:
      key: BACKBLAZE_SECRET_ACCESS_KEY
    secretKey: secretAccessKey
  - remoteRef:
      key: BACKBLAZE_BUCKET
    secretKey: bucket
  - remoteRef:
      key: BACKBLAZE_ENDPOINT
    secretKey: endpoint
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: backblaze-b2-creds

