apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: CLOUDFLARED_TOKEN
    secretKey: token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflared-ai-gateway

