apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: DOCKERHUB_USERNAME
    secretKey: username
  - remoteRef:
      key: DOCKERHUB_PASSWORD
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: dockerhub-credentials
    template:
      data:
        .dockerconfigjson: '{"auths":{"https://index.docker.io/v1/":{"username":"{{
          .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username
          .password | b64enc }}"}}}

          '
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson

