apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: ARGOCD_ADMIN_USERNAME
    secretKey: argocd-username
  - remoteRef:
      key: ARGOCD_ADMIN_PASSWORD
    secretKey: argocd-password
  - remoteRef:
      key: GITHUB_TOKEN
    secretKey: github-token
  - remoteRef:
      key: GATEWAY_GOTIFY_TOKEN
    secretKey: gotify-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gateway-credentials
