apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-alertmanager-external-secret
  namespace: monitoring
spec:
  data:
  - remoteRef:
      key: GOTIFY_ALERTMANAGER_TOKEN
    secretKey: gotify-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: gotify-alertmanager-token
