apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: groq-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: GROQ_API_KEY
    secretKey: api-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: groq-credentials

