apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keel-external-secret
  namespace: keel
spec:
  data:
  - remoteRef:
      key: KEEL_GOTIFY_TOKEN
    secretKey: GOTIFY_TOKEN
  - remoteRef:
      key: KEEL_GOTIFY_URL
    secretKey: GOTIFY_URL
  - remoteRef:
      key: KEEL_NOTIFICATION_GOTIFY_ADDRESS
    secretKey: KEEL_NOTIFICATION_GOTIFY_ADDRESS
  - remoteRef:
      key: KEEL_GOTIFY_TOKEN
    secretKey: KEEL_NOTIFICATION_GOTIFY_TOKEN
  - remoteRef:
      key: KEEL_WEBHOOK_ENDPOINT
    secretKey: WEBHOOK_ENDPOINT
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: keel

