apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-nextauth-external-secret
  namespace: langfuse
spec:
  data:
  - remoteRef:
      key: LANGFUSE_NEXTAUTH_SECRET
    secretKey: nextauth-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: langfuse-nextauth

