apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-redis-external-secret
  namespace: langfuse
spec:
  data:
  - remoteRef:
      key: REDIS_PASSWORD
    secretKey: redis-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: redis-secrets
