apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-salt-external-secret
  namespace: langfuse
spec:
  data:
  - remoteRef:
      key: LANGFUSE_SALT
    secretKey: salt
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: langfuse-salt
