apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-encryption-external-secret
  namespace: langfuse
spec:
  data:
  - remoteRef:
      key: LANGFUSE_ENCRYPTION_KEY
    secretKey: encryption-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: langfuse-encryption
