apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: intervalai:external-secrets.io/ExternalSecret:default/mongodb-backup-b2-credentials
  labels:
    app: mongodb-backup
  name: mongodb-backup-b2-credentials
  namespace: default
spec:
  data:
  - remoteRef:
      key: BACKBLAZE_ACCESS_KEY_ID
    secretKey: aws_access_key_id
  - remoteRef:
      key: BACKBLAZE_SECRET_ACCESS_KEY
    secretKey: aws_secret_access_key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: velero-b2-credentials

