apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-db-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: NEON_DATABASE_URL
    secretKey: DATABASE_URL
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: portfolio-db-secret

