apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-api-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: PORTFOLIO_ADMIN_USERNAME
    secretKey: admin-username
  - remoteRef:
      key: PORTFOLIO_ADMIN_PASSWORD
    secretKey: admin-password
  - remoteRef:
      key: PORTFOLIO_JWT_SECRET
    secretKey: jwt-secret
  - remoteRef:
      key: GOTIFY_APP_TOKEN
    secretKey: gotify-app-token
  - remoteRef:
      key: GOTIFY_CLIENT_TOKEN
    secretKey: gotify-client-token
  - remoteRef:
      key: NEON_DATABASE_URL
    secretKey: auth-database-url
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: portfolio-api-secrets

