apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-bookmarked-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: POSTGRESQL_BOOKMARKED_HOST
    secretKey: postgres-host
  - remoteRef:
      key: POSTGRESQL_BOOKMARKED_USER
    secretKey: postgres-user
  - remoteRef:
      key: POSTGRESQL_BOOKMARKED_DATABASE
    secretKey: postgres-database
  - remoteRef:
      key: POSTGRESQL_BOOKMARKED_PASSWORD
    secretKey: postgres-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgresql-bookmarked-secrets
