apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: runpod-external-secret
  namespace: default
spec:
  data:
  - remoteRef:
      key: RUNPOD_API_KEY
    secretKey: api-key
  - remoteRef:
      key: RUNPOD_ENDPOINT_ID
    secretKey: endpoint-id
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: runpod-credentials

