apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stremio-tailscale-external-secret
  namespace: stremio
spec:
  data:
    - remoteRef:
        key: STREMIO_TS_AUTHKEY
      secretKey: TS_AUTHKEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: stremio-tailscale-auth
