apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-cloud-credentials-external-secret
  namespace: velero
spec:
  data:
  - remoteRef:
      key: BACKBLAZE_ACCESS_KEY_ID
    secretKey: accessKeyID
  - remoteRef:
      key: BACKBLAZE_SECRET_ACCESS_KEY
    secretKey: secretAccessKey
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloud-credentials
    template:
      data:
        cloud: '[default]

          aws_access_key_id={{ .accessKeyID }}

          aws_secret_access_key={{ .secretAccessKey }}

          '
      engineVersion: v2
      mergePolicy: Replace

