apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  name: llama-cpu
  namespace: default
  labels:
    portfolio: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: llama-cpu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: llama-cpu
        portfolio: "true"
    spec:
      containers:
      - args:
        - -m
        - /models/llama-3.2-3b-instruct-q4_k_m.gguf
        - --host
        - 0.0.0.0
        - --port
        - "8080"
        - -c
        - "512"
        - -t
        - "6"
        - --batch-size
        - "512"
        - --n-predict
        - "100"
        - --mlock
        image: ghcr.io/ggml-org/llama.cpp:server
        imagePullPolicy: IfNotPresent
        name: llama-cpp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: models
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          if [ ! -f /models/llama-3.2-3b-instruct-q4_k_m.gguf ]; then
            curl -L -o /models/llama-3.2-3b-instruct-q4_k_m.gguf https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf?download=true
          else
            echo "Model already exists, skipping download"
          fi
        command:
        - /bin/sh
        - -c
        image: curlimages/curl
        imagePullPolicy: Always
        name: download-model
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: models
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ai-models-pvc
