apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: default
  labels:
    app: graphql-gateway
spec:
  type: ClusterIP
  selector:
    app: graphql-gateway
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    protocol: TCP
