apiVersion: v1
kind: Service
metadata:
  name: podrick-api
  namespace: default
  labels:
    app: podrick-api
spec:
  selector:
    app: podrick-api
  ports:
  - name: http
    port: 5001
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
