apiVersion: v1
kind: Service
metadata:
  name: portfolio-api
  namespace: default
  labels:
    app: portfolio-api
spec:
  type: ClusterIP
  selector:
    app: portfolio-api
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
