apiVersion: v1
kind: Service
metadata:
  name: tenantflow-frontend
  namespace: default
  labels:
    app: tenantflow-frontend
spec:
  type: ClusterIP
  selector:
    app: tenantflow-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
