apiVersion: v1
kind: Service
metadata:
  name: vertex-platform-auth
  namespace: default
  labels:
    app: vertex-platform-auth
    platform: vertex
spec:
  type: ClusterIP
  selector:
    app: vertex-platform-auth
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vertex-platform-analytics
  namespace: default
  labels:
    app: vertex-platform-analytics
    platform: vertex
spec:
  type: ClusterIP
  selector:
    app: vertex-platform-analytics
  ports:
  - name: http
    port: 3005
    targetPort: 3005
    protocol: TCP
